# Generated by Django 3.0.8 on 2020-08-12 13:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Seaport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('country', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipName', models.TextField()),
                ('imoNumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceType', models.TextField()),
                ('salesOrder', models.TextField()),
                ('budgetedAmount', models.TextField()),
                ('month', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2019), django.core.validators.MaxValueValidator(2500)])),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceControl.Client')),
                ('destiny', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destiny', to='serviceControl.Seaport')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceControl.Factory')),
                ('packing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing', to='serviceControl.Seaport')),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceControl.Ship')),
            ],
        ),
    ]
